version: "3"
services:
  learner:
    image: psub/learner
    # ports: 
    #   - "8081:8081"
    #   - "8080:8080"
    #   - "8090:8090"
    volumes:
      - .:/usr/src/app
    # environment:
    #   - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8081,server=y,suspend=n
    # environment:
    #   - JAVA_TOOL_OPTIONS=-Dserver.port=8090
    networks:
      - learner

networks:
  learner:
    external: true