FROM openjdk:17-oracle
VOLUME /usr/src/app
ARG EXTRACTED=target/extracted
COPY run.sh .
COPY ${EXTRACTED}/dependencies/ ./
COPY ${EXTRACTED}/spring-boot-loader/ ./
COPY ${EXTRACTED}/snapshot-dependencies/ ./
COPY ${EXTRACTED}/application/ ./
ENTRYPOINT ["./run.sh"]